### ISSUE TITLE
Item cannot be "uncollapsed"

### ISSUE THREAD

**Issue by wxv-martin** [melexis/sphinx-traceability-extension#191] opened 2020-11-06 10:52 UTC
With the option `traceability_collapse_links = True` the links contained in an item should be collapsed by default. Then, an arrow appears in the rendered output to allow the user to "uncollapse" the item.

It happens that arrow does not appear, making it impossible to read the links.

**Comment by JasperCraeghs** [comment] 2020-11-06 10:59
The arrow is there, but due to a recent change in our internal CSS stylesheet, the arrow has moved to a different location and become invisible.

**Comment by JasperCraeghs** [comment] 2020-11-06 13:14
This issue isn't caused by a change to our internal CSS stylesheet but by a upgrading sphinx-rtd-theme from 0.4.3 to 0.5.0. It's up to mlx.traceability to anticipate this behavior from external themes, so a fix is in order.

**Closed** 2020-11-06 16:26 UTC
